from . import excise_tax
from . import excise_tax_default
from . import account_tax
from . import res_partner
from . import sale_order_line
from . import account_move_line
from . import res_company
from . import res_config_settings
from . import sale_order
from . import account_move